# Find the NVML includes and library
#
# Once done this will define
#  NVML_INCLUDE_DIRS    - where to find NVML include files
#  NVML_LIBRARIES       - where to find NVML libs
#  NVML_FOUND           - True if NVML is found

SET(NVML_INC_PATHS /usr/include/nvidia/gdk/ /usr/include)
FIND_PATH(NVML_INCLUDE_DIR nvml.h PATHS ${NVML_INC_PATHS})
FIND_LIBRARY(NVML_LIBRARY nvidia-ml)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NVML DEFAULT_MSG NVML_INCLUDE_DIR NVML_LIBRARY)

SET(NVML_INCLUDE_DIRS ${NVML_INCLUDE_DIR})
SET(NVML_LIBRARIES ${NVML_LIBRARY})
IF(NOT NVML_LIBRARIES)
    SET(NVML_LIBRARIES "")
ENDIF()

MARK_AS_ADVANCED(NVML_INCLUDE_DIR NVML_LIBRARY)
